blank_issues_enabled: false
contact_links:
  - name: Project-Documentation

    about: Please ask and answer questions regarding the GitHub Platform here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities of the GitHub Platform here.
